# Generated by Django 5.2.7 on 2025-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'g'), ('Kg', 'Kg'), ('ml', 'ml'), ('L', 'L')], max_length=2),
        ),
    ]
