# Generated by Django 5.2.7 on 2026-02-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orana', '0002_alter_ingredients_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='constants',
            name='const_type',
            field=models.CharField(choices=[('c', 'currency'), ('i', 'integer'), ('p', 'percentage')], default='c', max_length=1),
        ),
    ]
